-- JOIN LV4 - 5월 식품들의 총 매출 조회하기

SELECT A.PRODUCT_ID, A.PRODUCT_NAME, TO_NUMBER(SUM(B.AMOUNT) * A.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT A
LEFT JOIN FOOD_ORDER B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE TO_CHAR(B.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID