SELECT A.FLAVOR
FROM (
    SELECT F.FLAVOR
        , SUM(J.TOTAL_ORDER) + SUM(F.TOTAL_ORDER) AS TORD
    FROM FIRST_HALF F
    INNER JOIN JULY J
    ON J.FLAVOR = F.FLAVOR
    GROUP BY F.FLAVOR
    ORDER BY TORD DESC) A
WHERE ROWNUM <= 3